# Uncomment this line to define a global platform for your project
platform :ios, '10.3'
#use_frameworks!

target 'RMF' do
  pod 'Reachability', '~> 3.2'
  pod 'MBProgressHUD', '~> 1.0.0'
  pod 'SDWebImage', '~> 4.3'
end

target 'RMF_CFL' do
  pod 'Reachability', '~> 3.2'
  pod 'MBProgressHUD', '~> 1.0.0'
  pod 'SDWebImage', '~> 4.3'
end
